### ISSUE TITLE
Adding extra label information

### ISSUE THREAD

**Issue by mkaranja** [ropensci/baRcodeR#22]
Hello,
When using the interactive custom_create_PDF() function, is it possible to include more information for the user which is not encoded in the barcode? for instance, when identifying plants, the barcode info is the plant-id and the genotype is label info shown to the user

custom_create_PDF(user = FALSE, Labels = **plant-id**, user_label=**genotype** name = "LabelsOut",
  type = "matrix", ErrCorr = "H", Fsz = 5, Across = TRUE,
  ERows = 0, ECols = 0, trunc = TRUE, numrow = 20, numcol = 4,
  page_width = 8.5, page_height = 11, width_margin = 0.25,
  height_margin = 0.5, x_space = 0, y_space = 0.5)

Thanks,
Margaret

**Comment by ColauttiLab** [comment]
HI Margaret,

No this is not currently possible because having different strings for the digital barcodes and human-readable text violates the principles of reproducible data collection that forms the basis of baRcodeR. A better way to handle this is to add the 'genotype' vector to the data.frame that contains 'plant-id' and print this out as a user reference or include it in a database.

Rob

**Comment by pbchase** [comment]
In my experience with clinical teams, nurses really like seeing redundant identifiers printed on the patient barcodes. Whereas the barcode encodes Jane Doe's medical record number and that MRN does appear under the barcode, the barcode also says "Jane Doe" to allow the nurses to double check that they have the right labels by asking the patient her name or reading an ID bracelet. Jane does not know her MRN, but she _does_ know her name. This allows a very fast recheck. 

As I build a research workflow that will deploy into a clinical environment I do wish I had the ability to add a datum or two that will _not_ be encoded into the barcode. We'll have to use a different tool to make the bar codes. It's a pity this one won't work when the rest of the RScript and workflows to get the right datasets to the lab are working so well.

**Comment by ColauttiLab** [comment]
This is a great use-case description Philip, thank you. I can see how this would be useful. I like Margaret's suggestion to encode the patent names as a separate column in the data.frame: one for Lables (e.g. plant ID, MRN), which generates the barcode, and another for the alt-text (e.g. genotype, patient names) that gets printed along side. 

I think we can try to get this into the next version release; the only question I have is how best to lay it out?

Do either of you (Philip, Margaret) have tag/label dimensions, and a diagram or picture showing the layout you would like to see? If so, we could incorporate them as alternative options to the current default layout.

**Comment by pbchase** [comment]
@ColauttiLab, thanks so much for following up. We're building a research workflow for COVID-19 testing. It would really benefit from this change. We are happy to be early adopters. I think it will reduce our error rate and speed the human workflows. 

Let me loop in the people who are working on the labels for our project--I'm just the supervising the developer that hit the wall when he found there was only one datum per label.  @ljwoodley, @senrabc, @KevinHanson, can you chime in on good arrangements and the data and the label sizes you are working with?

**Comment by ljwoodley** [comment]
<img width="178" alt="Screen Shot 2020-04-04 at 12 47 02 PM" src="https://user-images.githubusercontent.com/35935416/78456555-6620db00-7672-11ea-9eae-a61bae432e1b.png">

Here's a picture showing a possible layout where the `barcode_id` was used to generate the barcode and `alt_text` is another column in the dataframe containing the information that will not be encoded into the barcode. I can't think of specific dimensions but the default settings work quite well and the user can customize if necessary using `custom_create_pdf`.

**Comment by ColauttiLab** [comment]
Okay, this would be fairly easy to implement. I've also followed up with an email.

**Comment by KevinHanson** [comment]
Hi Everyone, I work with @ljwoodley for the COVID testing project we are launching Tuesday at 12. We have been working through iterations of various barcode label types. In the lab environment, we have a Tera HW0002 hand scanner that is capable of reading both 1D and 2D. However, the QR code curved around our 5ml tube renders the QR un-readable. So we have concluded for our purposes we need a 1D linear barcode. So we have the barcodeR software generating barcodes that scan rapidly and accurately on the Avery 5167 label template. This is the same as the line 1.75x.5 20-row template. We need the capability for a barcode that has the barcode ID, name of the person being tested, and the date of birth all on one label. Imagine a nurse see someone in a car drive up, ask for their license, and then verifies that the barcode label belongs to the right patient and then affixes the labels to the swab and blood vials at the moment of collection.

**Comment by KevinHanson** [comment]
Hi Everyone, I work with @ljwoodley for the COVID testing project we are launching Tuesday at 12. We have been working through iterations of various barcode label types. In the lab environment, we have a Tera HW0002 hand scanner that is capable of reading both 1D and 2D. However, the QR code curved around our 5ml tube renders the QR un-readable. So we have concluded for our purposes we need a 1D linear barcode. So we have the barcodeR software generating barcodes that scan rapidly and accurately on the Avery 5167 label template. This is the same as the line 1.75x.5 20-row template. We need the capability for a barcode that has the barcode ID, name of the person being tested, and the date of birth all on one label. Imagine a nurse see someone in a car drive up, ask for their license, and then verifies that the barcode label belongs to the right patient and then affixes the labels to the swab and blood vials at the moment of collection. So we want to be able to generate a barcode that looks like this:

![IMG_2191](https://user-images.githubusercontent.com/7871546/78463447-b582fd80-76aa-11ea-9a1f-65907cbc7620.jpg)

**Comment by ColauttiLab** [comment]
This change is now implemented in the current version on GitHub and will be pushed to CRAN following QA/QC:

```
devtools::install_github("ropensci/baRcodeR", build_vignettes = T)
library(baRcodeR)
```
 
`custom_create_PDF() now has two new parameters:`
 
`alt_text` vector containing alternative names that are printed along with Labels BUT ARE NOT ENCODED in the barcode image. Use with caution! 
`denote` character (prefix) or vector of length 2 (prefix, suffix). Denotes alt_text that is not encoded in the barcode image. Default is brackets before and after (). 
 
Here’s an example:
 
```
# test data
Test<-data.frame(ID=floor(runif(3)*10000),name=c("A","B","C"),dob=c("1/1/2020","12/6/2001", "2/8/1986"))
# example of new syntax
custom_create_PDF(Labels=Test$ID,alt_text=paste(Test$name,Test$dob))
# linear (1d) barcodes with custom denote
custom_create_PDF(Labels=Test$ID,alt_text=paste(Test$name,Test$dob),type="linear",denote=".")
```

```
## Include text for the user that is NOT encoded into the barcode image
## Excluded text is denoted with brackets by default
example_df <- data.frame(ID = floor(runif(3) * 10000), name = c("A", "B", "C"),
 dob = c("1/1/2020", "12/6/2001", "2/8/1986")
```
 
```
## linear (1d) barcodes with custom denote parameter
custom_create_PDF(Labels = example_df$ID, alt_text = paste(example_df$name,
 example_df$dob), type = "linear", denote=".")
```
