### ISSUE TITLE
Incorrect Alignment and Truncation

### ISSUE THREAD

**Issue by JEDamerow** [ropensci/baRcodeR#26]
I'm having some issues with the label alignment, in that after entering the label specifications exactly (actually some minor adjustments to better fit), the labels almost fit but the printing seems to migrate down and to the right. Is there a way to enter the vertical and horizontal pitch?  The truncation does not seem to quite work to stay within the labels, but maybe that would be fixed if there is a way to enter the pitch specifications.  

Label specifications are: 
![image](https://user-images.githubusercontent.com/47535114/113786106-586ebd00-96ed-11eb-8ea2-c415f46171e0.png)

I had to make some minor adjustments to the label specifications to make it fit better, but while it helps I still have the same issue with alignment and truncation. 

Here are the R scripts that I used most recently:

custom_create_PDF(user=FALSE, Labels = small_labels[,1], name = 'smallLabels_ParentMarch', 
                                     type = 'matrix', ErrCorr = 'Q', Fsz = 4.5, Across = TRUE, ERows = 0, 
                                     ECols = 0, trunc = TRUE, numrow = 17, numcol = 7, page_width = 8.5, 
                                     page_height = 11, width_margin = 0.54, height_margin = 0.15, 
                                     label_width = 0.94, label_height = 0.5, x_space = 0.1, y_space = 0.65)

And here are the Sample Ids that I am using

EAQ-2021-03-25
Rustlers-2021-03-25
Bradley-2021-03-25
Rock-2021-03-25
Copper-2021-03-25
EBC-2021-03-25
Copper-2021-03-30
EBC-2021-03-30
Copper-2021-04-07
EBC-2021-04-07
Rock-2021-04-07
Rustlers-2021-04-07
Bradley-2021-04-07
EAQ-2021-04-07

**Comment by yihanwu** [comment]
Hi @JEDamerow,

Here is what the output I get when running your code. 

![image](https://user-images.githubusercontent.com/25795885/113858435-bb099c80-9771-11eb-884d-f45ac65ff9dc.png)

When you say "migrating down and to the right," do you mean that the labels are not lining properly with the sticker sheet grid? Are all the columns/rows slightly off, or just some of the columns/rows? 

Also, if you are not using the package installed from github, do you mind trying to install from github and seeing if the problem persists?

**Comment by JEDamerow** [comment]
Somehow it has been two months, but I am finally revisiting this issue. Yes, the labels line up well in the first row of the sticker sheet, but each row moves slightly down until at the bottom the labels are printing out of alignment, and outside of the stickers.  

I installed the package from R, and will try to download from github.

**Comment by JEDamerow** [comment]
I tried installing from github and still having the same issue. Please let me know if you need more information. It works OK for the larger labels, but not for smaller labels (see dimensions above).

**Comment by sbonat** [comment]
I've had a similar problem, but I realized that it was the print settings that was throwing the alignment out of whack: when you are on the "print" screen make sure you select "Actual size" under Page Sizing and Handling and that the Orientation is Portrait. Also make sure that the printer page layout is set to the actual format of your label sheet, the default is A4 but for my labels it is letter (8.5 x 11 in)
Hope this helps!

**Comment by ColauttiLab** [comment]
Looks like this is a print setting, as noted in the documentation, so I'll mark this as closed
