### ISSUE TITLE
qrcode_gen() will be deprecated in qrcode 0.1.4

### ISSUE THREAD

**Issue by ThierryO** [ropensci/baRcodeR#28]
This is a hands up that `qrcode_gen()` is deprecated in qrcode 0.1.4 which I just submitted to CRAN.
The fix should be rather trivial:  use `qr_code()` instead of `qrcode_gen()` and match the new arguments.
`qr_code()` generated a logical matrix instead of a numeric vector.

https://github.com/ropensci/baRcodeR/blob/012b39109d004fe8a5dc2beaae5e811e4f2a62bd/R/hidden_createPDF.R#L458

**Comment by ColauttiLab** [comment]
will do for next release

**Comment by ThierryO** [comment]
I'm preparing version 0.2 in ThierryO/qrcode#12 which will defunct the legacy functions like `qrcode::qrcode_gen()`.
