### ISSUE TITLE
option to center QR code

### ISSUE THREAD

**Issue by lavaman13** [ropensci/baRcodeR#33]
This is not an issue but a request for added functionality.
I use circular labels (ex: https://www.labtag.com/shop/product/cryo-laser-labels-1-25-circle-cl-46/ ).  Currently the QR code produced with "create_PDF" is always shifted to the left of the label.  Is it possible to have an option to center the QR code on the label (for circular labels)?

Thanks for the great package, really useful!

Maxime

**Comment by ColauttiLab** [comment]
Thanks Maxime! I don't have anyone in the lab working on baRcodeR at the moment, but if you could email me an example csv, reproducible code, and pdf output that you use, I can see how hard it would be to try to make this work for you. If you are using the GUI plugin, you can copy-paste from the "Reproducible Code" window.

My email can be found on the 'People' page at EcoEvoGeno.org

**Comment by ColauttiLab** [comment]
Update: See https://github.com/ropensci/baRcodeR/issues/35#issuecomment-1918337905 for new feature allowing text centered above or below the label
