### ISSUE TITLE
underscores in 2D barcodes become hyphens

### ISSUE THREAD

**Issue by cfmw** [ropensci/baRcodeR#34]
Hello! Thanks for the great package. I've noticed when I generate 2D barcodes with text containing underscores, when I scan the barcodes, it is read as a hyphen upon scanning. Is it possible to include underscores in 2D barcode-encoded text? I've included an example; the underscore in the 4th position is read as a hyphen.

<img width="547" alt="Screenshot 2024-01-03 at 8 46 11 AM" src="https://github.com/ropensci/baRcodeR/assets/47062082/4002e13c-8f59-49f5-8cee-64b42f400990">

**Comment by ColauttiLab** [comment]
Glad you are finding it useful! 

This feature was added in 2018 (see [Issue 4](https://github.com/ropensci/baRcodeR/issues/4)) to deal with an error in the qr code generating function. However, these functions were updated so I checked again and I was able to generate a code with an underscore that worked with the qr detection of my iphone. I've pushed this change to GitHub for trial use. 

Before we update this on CRAN, would you mind testing it out with your labels and equipment to make sure you aren’t getting any errors or having other problems?

To install the edited version, first quit and restart R (and RStudio, etc.) to clear the memory and install the GitHub version: You might have to first install devtools if you don’t already have it:
`install.packages("devtools")`

And then use devtools to install the updated GitHub version of baRcodeR:
`devtools::install_github("ropensci/baRcodeR")`

Finally, load the downloaded baRcodeR library to replace the cran version:
`library(baRcodeR)`

If/when you want to switch back to the CRAN version, restart R again, then re-install and load from CRAN:
```
install.packages("baRcodeR")
library(baRcodeR)
```
