### ISSUE TITLE
[Feature request] fitting the labels to Tough Spots 

### ISSUE THREAD

**Issue by wolass** [ropensci/baRcodeR#35]
Dear Authors,
I am once again underlining the importance of your valuable work, by using it exensively in our Lab for biosamples.
Thank you for the package it really is the only one that is currently useful for this purpose. 
 
I have however a bit of a problem, because we would like to use a different format for our labels that is ot currently supported by the package. 

Would it be possible to implement a couple of additional features to utilize the following paper for the label printing? 
https://www.divbio.com/category/laser-tough-spots
Im mostly interested in the SPOT-5000 format. 

This requires that we would move the label underneath the QR code and center the label. 
I currently do not know how to change the code to implement this feature and would be greatful for your help.
I think this would also increase the usefulness of the package for the general public.

**Comment by ColauttiLab** [comment]
Thanks! We love to hear how baRcodeR is working in the wild. Your request is very similar to @lavaman13 in #33 so clearly there is some need here. I'm a bit rusty with the code that @yihanwu wrote, but I think it works now. Please test it out with your samples and let me know how it goes (preferably by email: see EcoEvoGeno.org/people.html for email). Let me know how it works and if you have any issues before we push this new version to CRAN for the masses.

To install the edited version, first quit and restart R (and RStudio, etc.) to clear the memory and install the GitHub version: You might have to first install devtools if you don’t already have it:
`install.packages("devtools")`

And then use devtools to install the updated GitHub version of baRcodeR:
`devtools::install_github("ropensci/baRcodeR")`

Finally, load the downloaded baRcodeR library to replace the cran version:
`library(baRcodeR)`

If/when you want to switch back to the CRAN version, restart R again, then re-install and load from CRAN:
```
install.packages("baRcodeR")
library(baRcodeR)
```

Once you install the GitHub version, you should see an option for `matrix2` in the help `?create_PDF`

Use the `y_space` argument to put text below (`y_space = 0`) or above (`y_space = 1`) the QR barcode. 

You should also be able to do this with the baRcodeR GUI app in the Addins menu. 

<img width="429" alt="R Studio menu bar with the Addins menu" src="https://github.com/ropensci/baRcodeR/assets/17328412/661ac194-745e-4d89-8800-985372093f25">

Choose QR code (inline-text)

<img width="429" alt="baRcodeR GUI window with new Barcode Type options" src="https://github.com/ropensci/baRcodeR/assets/17328412/48509ef5-5f14-4559-8f0c-8f6ffef2a220">

Then, scroll down and set vertical location to 0 (below QR code)

<img height="429" alt="baRcodeR GUI window with parameter for text location" src="https://github.com/ropensci/baRcodeR/assets/17328412/c71c3b02-64e8-43a5-9b1a-c77062c2135c">
